### ISSUE TITLE
Amazing work on the app

### ISSUE THREAD

**Issue by mdhishaamakhtar** [Fool-Stack/CodEd-App#1]
I cannot begin to explain how amazing the application was. It was the best thing I'd ever seen in my life. Great job man.

**Comment by N0v0cain3** [comment]
🧂🧂🧂🧂🧂🧂🧂🧂🧂🧂🧂

**Comment by N0v0cain3** [comment]
Thanks to us we didn't come to Access Denied with the same idea @mdhishaamakhtar
